// Generated by AI for proof of concept
import type {
  Difficulty,
  GeneralLengthConstraint as Length,
  ValidationSuccess,
} from '../types';

const themeTwisters: Record<
  string,
  Record<Length, Record<Difficulty, string>>
> = {
  sea: {
    short: {
      easy: 'Sly sea slugs slide softly.',
      medium: 'Sleek sea seals slide swiftly.',
      hard: 'Swift sea swans swish, slosh.',
      expert: 'Seething sea swans swiftly swish, slosh.',
    },
    medium: {
      easy: 'Slick sea slugs slide swiftly by salty shores.',
      medium: 'Sleek sea seals slide past salty shoals steadily.',
      hard: 'Stormy sea swans swirl, splashing slick shells and shoals.',
      expert: 'Stormy sea swans swirl, splashing slick shells, shoals, skiffs.',
    },
    long: {
      easy: 'Slick sea slugs slide swiftly by salty shores, seeking shiny shells today.',
      medium:
        'Sleek sea seals slide past salty shoals, seeking smooth stones nearby today.',
      hard: 'Stormy sea swans swirl, splashing slick shells and shoals while sailors steer.',
      expert:
        'Stormy sea swans swirl, splashing slick shells, shoals, skiffs while sailors steer.',
    },
  },
  cooking: {
    short: {
      easy: 'Silly chefs chop chili.',
      medium: 'Clever chefs chop chili quickly.',
      hard: 'Crisp crusts crack, clatter, crumble.',
      expert: 'Crisp crusts crackle, clatter, crumble.',
    },
    medium: {
      easy: 'Clever cooks cut carrots, coat pans, and stir steadily.',
      medium: 'Clever cooks cut carrots, coat pans, stir steadily.',
      hard: 'Crisp crusts crackle as crafty chefs chop charred chiles.',
      expert:
        'Crisp crusts crackle as crafty chefs chop charred chiles quickly.',
    },
    long: {
      easy: 'Clever cooks cut carrots, coat pans, and stir stews for supper slowly.',
      medium:
        'Clever cooks cut carrots, coat pans, stir stews for supper slowly today.',
      hard: 'Crisp crusts crackle as crafty chefs chop charred chiles with clattering knives.',
      expert:
        'Crisp crusts crackle as crafty chefs chop charred chiles with clattering, clinking knives.',
    },
  },
  space: {
    short: {
      easy: 'Starry skies spin slowly.',
      medium: 'Starry ships spin silently.',
      hard: 'Spaced ships shift, shimmer, shudder.',
      expert: 'Spaced ships shift, shimmer, shudder sharply.',
    },
    medium: {
      easy: 'Silent star sailors steer silver ships through soft starlight.',
      medium:
        'Silent star sailors steer silver ships through steady starlight.',
      hard: 'Spaced pilots spin past spirals, skimming swift stellar streams.',
      expert:
        'Spaced pilots spin past spirals, skimming swift stellar streams swiftly.',
    },
    long: {
      easy: 'Silent star sailors steer silver ships through soft starlight and steady streams.',
      medium:
        'Silent star sailors steer silver ships through steady starlight and streaming skies.',
      hard: 'Spaced pilots spin past spirals, skimming swift stellar streams and shadowy stations.',
      expert:
        'Spaced pilots spin past spirals, skimming swift stellar streams and shadowy stations swiftly.',
    },
  },
  music: {
    short: {
      easy: 'Merry melodies move minds.',
      medium: 'Mellow melodies move minds.',
      hard: 'Sharp strings strike, shimmer, sing.',
      expert: 'Sharp strings strike, shimmer, sing sharply.',
    },
    medium: {
      easy: 'Mellow musicians make merry melodies, moving many minds.',
      medium: 'Mellow musicians make mellow melodies, moving many minds.',
      hard: 'Sharp strings strike, shimmering scales skip swiftly through silent halls.',
      expert:
        'Sharp strings strike, shimmering scales skip swiftly through silent halls, singing.',
    },
    long: {
      easy: 'Mellow musicians make merry melodies, moving many minds with measured beats today.',
      medium:
        'Mellow musicians make mellow melodies, moving many minds with measured beats today.',
      hard: 'Sharp strings strike, shimmering scales skip swiftly through silent halls and stages.',
      expert:
        'Sharp strings strike, shimmering scales skip swiftly through silent halls and stages, singing.',
    },
  },
  sports: {
    short: {
      easy: 'Swift strikers score smoothly.',
      medium: 'Swift strikers sprint smoothly.',
      hard: 'Stout sprinters stretch, sprint, surge.',
      expert: 'Stout sprinters stretch, sprint, surge swiftly.',
    },
    medium: {
      easy: 'Swift strikers sprint, score, and celebrate smooth victories.',
      medium: 'Swift strikers sprint, score, and celebrate steady victories.',
      hard: 'Stout sprinters stretch, sprint, and surge past stubborn starters.',
      expert:
        'Stout sprinters stretch, sprint, and surge past stubborn starters swiftly.',
    },
    long: {
      easy: 'Swift strikers sprint, score, and celebrate smooth victories with steady stamina today.',
      medium:
        'Swift strikers sprint, score, and celebrate steady victories with steady stamina today.',
      hard: 'Stout sprinters stretch, sprint, and surge past stubborn starters and stiff stadium steps.',
      expert:
        'Stout sprinters stretch, sprint, and surge past stubborn starters and stiff stadium steps swiftly.',
    },
  },
  animals: {
    short: {
      easy: 'Fuzzy foxes frisk fast.',
      medium: 'Fuzzy foxes frisk freely.',
      hard: 'Bristled bears bellow, bound, bash.',
      expert: 'Bristled bears bellow, bound, bash boldly.',
    },
    medium: {
      easy: 'Fuzzy foxes flutter through fields, following friendly fawns.',
      medium:
        'Fuzzy foxes flutter through fields, following friendly forest friends.',
      hard: 'Bristled bears bellow, bounding boldly beyond broken branches.',
      expert:
        'Bristled bears bellow, bounding boldly beyond broken branches and brambles.',
    },
    long: {
      easy: 'Fuzzy foxes flutter through fields, following friendly fawns and feisty ferrets nearby.',
      medium:
        'Fuzzy foxes flutter through fields, following friendly forest friends and feisty ferrets nearby.',
      hard: 'Bristled bears bellow, bounding boldly beyond broken branches and bristly bushes today.',
      expert:
        'Bristled bears bellow, bounding boldly beyond broken branches and bristly bushes by brookbanks.',
    },
  },
};

const toThemeKey = (theme: string): string => {
  const normalized = theme.toLowerCase();
  const keys = Object.keys(themeTwisters);

  return keys.find(key => normalized.includes(key)) ?? 'generic';
};

const toThemeToken = (theme: string): string => {
  const rawToken = theme.trim().split(/\s+/)[0];
  const token = rawToken && rawToken.length > 0 ? rawToken : 'Twisty';
  return token.charAt(0).toUpperCase() + token.slice(1);
};

const fallbackTwister = (
  theme: string,
  length: Length,
  difficulty: Difficulty
): string => {
  const token = toThemeToken(theme);

  const fallbackMap: Record<Length, Record<Difficulty, string>> = {
    short: {
      easy: `${token} sprites spin softly.`,
      medium: `${token} sprites spin smoothly.`,
      hard: `${token} sprinters swerve, sprint, surge.`,
      expert: `${token} sprinters swerve, sprint, surge swiftly.`,
    },
    medium: {
      easy: `${token} sprites spin softly, sending subtle sounds today.`,
      medium: `${token} sprites spin smoothly, sending subtle sounds today.`,
      hard: `${token} sprinters swerve, sprint, and surge past stubborn steps.`,
      expert: `${token} sprinters swerve, sprint, and surge past stubborn steps swiftly.`,
    },
    long: {
      easy: `${token} sprites spin softly, sending subtle sounds to sleepy souls nearby today.`,
      medium: `${token} sprites spin smoothly, sending subtle sounds to sleepy souls nearby today.`,
      hard: `${token} sprinters swerve, sprint, and surge past stubborn steps and stiff stones.`,
      expert: `${token} sprinters swerve, sprint, and surge past stubborn steps and stiff stones swiftly.`,
    },
  };

  return fallbackMap[length][difficulty];
};

export const getPlaceholderTwister = ({
  theme,
  length,
  difficulty,
}: ValidationSuccess['value']): string => {
  const themeKey = toThemeKey(theme);

  if (themeKey === 'generic') {
    return fallbackTwister(theme, length, difficulty);
  }

  const themeEntry = themeTwisters[themeKey];

  if (!themeEntry) {
    return fallbackTwister(theme, length, difficulty);
  }

  return themeEntry[length][difficulty];
};
